symfonycasts_reset_password:
    request_password_repository: Viewpoint\AdminBundle\Repository\ResetPasswordRequestRepository
    lifetime: 3600
    throttle_limit: 600
    enable_garbage_collection: true
