<?php

$currenciesList = [
    ['name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$', 'exchangeRate' => 1.0],
    ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€', 'exchangeRate' => 0.85],
    ['name' => 'British Pound', 'code' => 'GBP', 'symbol' => '£', 'exchangeRate' => 0.73],
    ['name' => 'Japanese Yen', 'code' => 'JPY', 'symbol' => '¥', 'exchangeRate' => 110.0],
    ['name' => 'Canadian Dollar', 'code' => 'CAD', 'symbol' => 'CA$', 'exchangeRate' => 1.25],
    ['name' => 'Swiss Franc', 'code' => 'CHF', 'symbol' => 'CHF', 'exchangeRate' => 0.92],
    ['name' => 'Chinese Yuan Renminbi', 'code' => 'CNY', 'symbol' => '¥', 'exchangeRate' => 6.45],
    ['name' => 'South Korean Won', 'code' => 'KRW', 'symbol' => '₩', 'exchangeRate' => 1200.0],
    ['name' => 'South African Rand', 'code' => 'ZAR', 'symbol' => 'R', 'exchangeRate' => 14.0],
    ['name' => 'Turkish Lira', 'code' => 'TRY', 'symbol' => '₺', 'exchangeRate' => 8.75],
    ['name' => 'Hong Kong Dollar', 'code' => 'HKD', 'symbol' => 'HK$', 'exchangeRate' => 7.80],
    ['name' => 'Singapore Dollar', 'code' => 'SGD', 'symbol' => 'S$', 'exchangeRate' => 1.33],
    ['name' => 'Saudi Riyal', 'code' => 'SAR', 'symbol' => '﷼', 'exchangeRate' => 3.75],
    ['name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'CFA', 'exchangeRate' => 560.0],
    ['name' => 'Moroccan Dirham', 'code' => 'MAD', 'symbol' => 'MAD', 'exchangeRate' => 8.90],
];


$citiesData = [
    'United States' => [
        ['name' => 'New York', 'country' => 'United States'],
        ['name' => 'Los Angeles', 'country' => 'United States'],
        ['name' => 'Chicago', 'country' => 'United States'],
        ['name' => 'Houston', 'country' => 'United States'],
        ['name' => 'Phoenix', 'country' => 'United States'],
        ['name' => 'Philadelphia', 'country' => 'United States'],
        ['name' => 'San Antonio', 'country' => 'United States'],
        ['name' => 'San Diego', 'country' => 'United States'],
        ['name' => 'Dallas', 'country' => 'United States'],
        ['name' => 'San Jose', 'country' => 'United States'],
        ['name' => 'Austin', 'country' => 'United States'],
        ['name' => 'Jacksonville', 'country' => 'United States'],
        ['name' => 'Fort Worth', 'country' => 'United States'],
        ['name' => 'Columbus', 'country' => 'United States'],
        ['name' => 'Indianapolis', 'country' => 'United States'],
        ['name' => 'Charlotte', 'country' => 'United States'],
        ['name' => 'San Francisco', 'country' => 'United States'],
        ['name' => 'Seattle', 'country' => 'United States'],
        ['name' => 'Denver', 'country' => 'United States'],
        ['name' => 'Washington DC', 'country' => 'United States'],
        ['name' => 'Nashville', 'country' => 'United States'],
        ['name' => 'Oklahoma City', 'country' => 'United States'],
        ['name' => 'El Paso', 'country' => 'United States'],
        ['name' => 'Boston', 'country' => 'United States'],
        ['name' => 'Portland', 'country' => 'United States'],
        ['name' => 'Las Vegas', 'country' => 'United States'],
        ['name' => 'Detroit', 'country' => 'United States'],
        ['name' => 'Louisville', 'country' => 'United States'],
        ['name' => 'Memphis', 'country' => 'United States'],
        ['name' => 'Baltimore', 'country' => 'United States'],
        ['name' => 'Milwaukee', 'country' => 'United States'],
        ['name' => 'Albuquerque', 'country' => 'United States'],
        ['name' => 'Fresno', 'country' => 'United States'],
        ['name' => 'Tucson', 'country' => 'United States'],
        ['name' => 'Sacramento', 'country' => 'United States'],
        ['name' => 'Kansas City', 'country' => 'United States'],
        ['name' => 'Mesa', 'country' => 'United States'],
        ['name' => 'Atlanta', 'country' => 'United States'],
        ['name' => 'Omaha', 'country' => 'United States'],
        ['name' => 'Colorado Springs', 'country' => 'United States'],
        ['name' => 'Raleigh', 'country' => 'United States'],
        ['name' => 'Long Beach', 'country' => 'United States'],
        ['name' => 'Virginia Beach', 'country' => 'United States'],
        ['name' => 'Miami', 'country' => 'United States'],
        ['name' => 'Oakland', 'country' => 'United States'],
        ['name' => 'Minneapolis', 'country' => 'United States'],
        ['name' => 'Tulsa', 'country' => 'United States'],
        ['name' => 'Bakersfield', 'country' => 'United States'],
        ['name' => 'Wichita', 'country' => 'United States'],
        ['name' => 'Arlington', 'country' => 'United States'],
        ['name' => 'Aurora', 'country' => 'United States'],
        ['name' => 'New Orleans', 'country' => 'United States'],
        ['name' => 'Tampa', 'country' => 'United States'],
        ['name' => 'Cleveland', 'country' => 'United States'],
        ['name' => 'Cincinnati', 'country' => 'United States'],
        ['name' => 'Orlando', 'country' => 'United States'],
        ['name' => 'North Las Vegas', 'country' => 'United States'],
        ['name' => 'St. Petersburg', 'country' => 'United States'],
        ['name' => 'Rochester', 'country' => 'United States'],
        ['name' => 'Birmingham', 'country' => 'United States'],
        ['name' => 'Fayetteville', 'country' => 'United States'],
        ['name' => 'Moreno Valley', 'country' => 'United States'],
        ['name' => 'Fontana', 'country' => 'United States'],
        ['name' => 'Columbus (Georgia)', 'country' => 'United States'],
    ],
    'United Kingdom' => [
        ['name' => 'London', 'country' => 'United Kingdom'],
        ['name' => 'Birmingham', 'country' => 'United Kingdom'],
        ['name' => 'Glasgow', 'country' => 'United Kingdom'],
        ['name' => 'Manchester', 'country' => 'United Kingdom'],
        ['name' => 'Edinburgh', 'country' => 'United Kingdom'],
        ['name' => 'Liverpool', 'country' => 'United Kingdom'],
        ['name' => 'Leeds', 'country' => 'United Kingdom'],
        ['name' => 'Bristol', 'country' => 'United Kingdom'],
        ['name' => 'Sheffield', 'country' => 'United Kingdom'],
        ['name' => 'Newcastle', 'country' => 'United Kingdom'],
        ['name' => 'Coventry', 'country' => 'United Kingdom'],
        ['name' => 'Cardiff', 'country' => 'United Kingdom'],
        ['name' => 'Kingston upon Hull', 'country' => 'United Kingdom'],
        ['name' => 'Stoke-on-Trent', 'country' => 'United Kingdom'],
        ['name' => 'Leicester', 'country' => 'United Kingdom'],
        ['name' => 'Southampton', 'country' => 'United Kingdom'],
        ['name' => 'Reading', 'country' => 'United Kingdom'],
        ['name' => 'Plymouth', 'country' => 'United Kingdom'],
    ],
    'France' => [
        ['name' => 'Paris', 'country' => 'France'],
        ['name' => 'Marseille', 'country' => 'France'],
        ['name' => 'Lyon', 'country' => 'France'],
        ['name' => 'Toulouse', 'country' => 'France'],
        ['name' => 'Nice', 'country' => 'France'],
        ['name' => 'Nantes', 'country' => 'France'],
        ['name' => 'Strasbourg', 'country' => 'France'],
        ['name' => 'Montpellier', 'country' => 'France'],
        ['name' => 'Bordeaux', 'country' => 'France'],
        ['name' => 'Lille', 'country' => 'France'],
        ['name' => 'Rennes', 'country' => 'France'],
        ['name' => 'Reims', 'country' => 'France'],
        ['name' => 'Le Havre', 'country' => 'France'],
        ['name' => 'Saint-Étienne', 'country' => 'France'],
        ['name' => 'Toulon', 'country' => 'France'],
        ['name' => 'Grenoble', 'country' => 'France'],
        ['name' => 'Angers', 'country' => 'France'],
        ['name' => 'Dijon', 'country' => 'France'],
        ['name' => 'Brest', 'country' => 'France'],
        ['name' => 'Le Mans', 'country' => 'France'],
        ['name' => 'Nîmes', 'country' => 'France'],
        ['name' => 'Aix-en-Provence', 'country' => 'France'],
        ['name' => 'Clermont-Ferrand', 'country' => 'France'],
        ['name' => 'Tours', 'country' => 'France'],
        ['name' => 'Amiens', 'country' => 'France'],
        ['name' => 'Limoges', 'country' => 'France'],
        ['name' => 'Villeurbanne', 'country' => 'France'],
        ['name' => 'Metz', 'country' => 'France'],
        ['name' => 'Besançon', 'country' => 'France'],
        ['name' => 'Perpignan', 'country' => 'France'],
        ['name' => 'Orléans', 'country' => 'France'],
        ['name' => 'Caen', 'country' => 'France'],
        ['name' => 'Mulhouse', 'country' => 'France'],
        ['name' => 'Boulogne-Billancourt', 'country' => 'France'],
        ['name' => 'Rouen', 'country' => 'France'],
        ['name' => 'Nancy', 'country' => 'France'],
        ['name' => 'Argenteuil', 'country' => 'France'],
        ['name' => 'Montreuil', 'country' => 'France'],
        ['name' => 'Saint-Denis', 'country' => 'France'],
        ['name' => 'Roubaix', 'country' => 'France'],
        ['name' => 'Avignon', 'country' => 'France'],
        ['name' => 'Tourcoing', 'country' => 'France'],
        ['name' => 'Poitiers', 'country' => 'France'],
        ['name' => 'Nanterre', 'country' => 'France'],
        ['name' => 'Créteil', 'country' => 'France'],
        ['name' => 'Versailles', 'country' => 'France'],
        ['name' => 'Pau', 'country' => 'France'],
        ['name' => 'Courbevoie', 'country' => 'France'],
        ['name' => 'Vitry-sur-Seine', 'country' => 'France'],
        ['name' => 'Asnières-sur-Seine', 'country' => 'France'],
        ['name' => 'Colombes', 'country' => 'France'],
        ['name' => 'Aulnay-sous-Bois', 'country' => 'France'],
        ['name' => 'La Rochelle', 'country' => 'France'],
        ['name' => 'Rueil-Malmaison', 'country' => 'France'],
        ['name' => 'Antibes', 'country' => 'France'],
        ['name' => 'Saint-Maur-des-Fossés', 'country' => 'France'],
        ['name' => 'Calais', 'country' => 'France'],
        ['name' => 'Champigny-sur-Marne', 'country' => 'France'],
        ['name' => 'Aubervilliers', 'country' => 'France'],
        ['name' => 'Béziers', 'country' => 'France'],
        ['name' => 'Bourges', 'country' => 'France'],
        ['name' => 'Cannes', 'country' => 'France'],
        ['name' => 'Saint-Nazaire', 'country' => 'France'],
        ['name' => 'Dunkerque', 'country' => 'France'],
        ['name' => 'Quimper', 'country' => 'France'],
        ['name' => 'Valence', 'country' => 'France'],
        ['name' => 'Colmar', 'country' => 'France'],
        ['name' => 'Drancy', 'country' => 'France'],
        ['name' => 'Mérignac', 'country' => 'France'],
        ['name' => 'Ajaccio', 'country' => 'France'],
        ['name' => 'Levallois-Perret', 'country' => 'France'],
        ['name' => 'Troyes', 'country' => 'France'],
        ['name' => 'Neuilly-sur-Seine', 'country' => 'France'],
        ['name' => 'Issy-les-Moulineaux', 'country' => 'France'],
        ['name' => 'Villeneuve-d\'Ascq', 'country' => 'France'],
        ['name' => 'Noisy-le-Grand', 'country' => 'France'],
        ['name' => 'Antony', 'country' => 'France'],
        ['name' => 'Niort', 'country' => 'France'],
        ['name' => 'Lorient', 'country' => 'France'],
        ['name' => 'Sarcelles', 'country' => 'France'],
        ['name' => 'Chambéry', 'country' => 'France'],
        ['name' => 'Saint-Quentin', 'country' => 'France'],
        ['name' => 'Pessac', 'country' => 'France'],
        ['name' => 'Vénissieux', 'country' => 'France'],
        ['name' => 'Cergy', 'country' => 'France'],
        ['name' => 'La Seyne-sur-Mer', 'country' => 'France'],
        ['name' => 'Clichy', 'country' => 'France'],
        ['name' => 'Beauvais', 'country' => 'France'],
        ['name' => 'Cholet', 'country' => 'France'],
        ['name' => 'Hyères', 'country' => 'France'],
        ['name' => 'Ivry-sur-Seine', 'country' => 'France'],
        ['name' => 'Montauban', 'country' => 'France'],
        ['name' => 'Vannes', 'country' => 'France'],
        ['name' => 'La Roche-sur-Yon', 'country' => 'France'],
        ['name' => 'Charleville-Mézières', 'country' => 'France'],
        ['name' => 'Pantin', 'country' => 'France'],
        ['name' => 'Laval', 'country' => 'France'],
        ['name' => 'Maisons-Alfort', 'country' => 'France'],
        ['name' => 'Bondy', 'country' => 'France'],
        ['name' => 'Évry', 'country' => 'France'],
    ],
    'Japan' => [
        ['name' => 'Tokyo', 'country' => 'Japan'],
        ['name' => 'Osaka', 'country' => 'Japan'],
        ['name' => 'Kyoto', 'country' => 'Japan'],
        ['name' => 'Nagoya', 'country' => 'Japan'],
        ['name' => 'Sapporo', 'country' => 'Japan'],
    ],
    'China' => [
        ['name' => 'Beijing', 'country' => 'China'],
        ['name' => 'Shanghai', 'country' => 'China'],
        ['name' => 'Guangzhou', 'country' => 'China'],
        ['name' => 'Shenzhen', 'country' => 'China'],
        ['name' => 'Chongqing', 'country' => 'China'],
    ],
    'Senegal' => [
        ['name' => 'Dakar', 'country' => 'Senegal'],
        ['name' => 'Thiès', 'country' => 'Senegal'],
        ['name' => 'Kaolack', 'country' => 'Senegal'],
        ['name' => 'Saint-Louis', 'country' => 'Senegal'],
        ['name' => 'Ziguinchor', 'country' => 'Senegal'],
        ['name' => 'Tambacounda', 'country' => 'Senegal'],
        ['name' => 'Diourbel', 'country' => 'Senegal'],
        ['name' => 'Louga', 'country' => 'Senegal'],
        ['name' => 'Kolda', 'country' => 'Senegal'],
        ['name' => 'Fatick', 'country' => 'Senegal'],
        ['name' => 'Sédhiou', 'country' => 'Senegal'],
        ['name' => 'Kaffrine', 'country' => 'Senegal'],
        ['name' => 'Kédougou', 'country' => 'Senegal'],
        ['name' => 'Rufisque', 'country' => 'Senegal'],
        ['name' => 'Mbour', 'country' => 'Senegal'],
        ['name'=> 'Ouakam', 'country' => 'Senegal'],
        ['name'=> 'Mbao', 'country' => 'Senegal'],
        ['name'=> 'Yoff', 'country' => 'Senegal'],
        ['name'=> 'Point E', 'country' => 'Senegal'],
        ['name'=> 'Scat Urbam', 'country' => 'Senegal'],
        ['name'=> 'Guediawaye', 'country'=> 'Senegal'],
        ['name' => 'Touba', 'country'=> 'Senegal' ],
        ['name'=> 'Keur Massar', 'country'=> 'Senegal'],
        ['name'=> 'Zac Mbao', 'country'=> 'Senegal'],
        ['name' => 'Mbour', 'country'=> 'Senegal'],
        ['name' => 'Medina', 'country'=> 'Senegal'],
        ['name' => 'Nord Foire', 'country'=> 'Senegal'],
        ['name' => 'Ouest Foire', 'country'=> 'Senegal'],
        ['name' => 'Grand Yoff', 'country'=> 'Senegal'],
        ['name' => 'Patte d\'oie', 'country'=> 'Senegal']
    ],
    'Mali' => [
        ['name' => 'Bamako', 'country' => 'Mali'],
        ['name' => 'Sikasso', 'country' => 'Mali'],
        ['name' => 'Mopti', 'country' => 'Mali'],
        ['name' => 'Koutiala', 'country' => 'Mali'],
        ['name' => 'Kayes', 'country' => 'Mali'],
        ['name' => 'Ségou', 'country' => 'Mali'],
        ['name' => 'Gao', 'country' => 'Mali'],
        ['name' => 'Markala', 'country' => 'Mali'],
        ['name' => 'Kolokani', 'country' => 'Mali'],
        ['name' => 'Kati', 'country' => 'Mali'],
        ['name' => 'Koulikoro', 'country' => 'Mali'],
        ['name' => 'Niono', 'country' => 'Mali'],
        ['name' => 'Yorosso', 'country' => 'Mali'],
        ['name' => 'Bougouni', 'country' => 'Mali'],
        ['name' => 'Timbuktu', 'country' => 'Mali'],
        ['name' => 'Banamba', 'country' => 'Mali'],
        ['name' => 'Bafoulabé', 'country' => 'Mali'],
        ['name' => 'San', 'country' => 'Mali'],
        ['name' => 'Kidal', 'country' => 'Mali'],
        ['name' => 'Bla', 'country' => 'Mali'],
        ['name' => 'Goundam', 'country' => 'Mali'],
        ['name' => 'Douentza', 'country' => 'Mali'],
        ['name' => 'Araouane', 'country' => 'Mali'],
        ['name' => 'Bafoulabé', 'country' => 'Mali'],
        ['name' => 'Kati', 'country' => 'Mali'],
        ['name' => 'Sikasso', 'country' => 'Mali'],
        ['name' => 'Mopti', 'country' => 'Mali'],
        ['name' => 'Tessalit', 'country' => 'Mali'],
        ['name' => 'Ansongo', 'country' => 'Mali'],
        ['name' => 'Kidal', 'country' => 'Mali'],
        ['name' => 'Bamako', 'country' => 'Mali'],
        ['name' => 'Gao', 'country' => 'Mali'],
        ['name' => 'Bougouni', 'country' => 'Mali'],
        ['name' => 'Bla', 'country' => 'Mali'],
        ['name' => 'Bandiagara', 'country' => 'Mali'],
        ['name' => 'Nara', 'country' => 'Mali'],
        ['name' => 'San', 'country' => 'Mali'],
        ['name' => 'Markala', 'country' => 'Mali'],
        ['name' => 'Djenné', 'country' => 'Mali'],
        ['name' => 'Tombouctou', 'country' => 'Mali'],
        ['name' => 'Goundam', 'country' => 'Mali'],
        ['name' => 'Koutiala', 'country' => 'Mali'],
        ['name' => 'Niono', 'country' => 'Mali'],
        ['name' => 'Ségou', 'country' => 'Mali'],
        ['name' => 'Niono', 'country' => 'Mali'],
        ['name' => 'Yorosso', 'country' => 'Mali'],
        ['name' => 'Koulikoro', 'country' => 'Mali'],
        ['name' => 'Kolokani', 'country' => 'Mali'],
        ['name' => 'Kidal', 'country' => 'Mali'],
        ['name' => 'Bamako', 'country' => 'Mali'],
        ['name' => 'Gao', 'country' => 'Mali'],
        ['name' => 'Tessalit', 'country' => 'Mali'],
        ['name' => 'Ansongo', 'country' => 'Mali'],
        ['name' => 'Kati', 'country' => 'Mali'],
        ['name' => 'Bougouni', 'country' => 'Mali'],
        ['name' => 'Bla', 'country' => 'Mali'],
        ['name' => 'Bandiagara', 'country' => 'Mali'],
        ['name' => 'Nara', 'country' => 'Mali'],
        ['name' => 'San', 'country' => 'Mali'],
        ['name' => 'Markala', 'country' => 'Mali'],
        ['name' => 'Djenné', 'country' => 'Mali'],
        ['name' => 'Tombouctou', 'country' => 'Mali'],
        ['name' => 'Goundam', 'country' => 'Mali'],
        ['name' => 'Koutiala', 'country' => 'Mali'],
        ['name' => 'Niono', 'country' => 'Mali'],
        ['name' => 'Ségou', 'country' => 'Mali'],
        ['name' => 'Yorosso', 'country' => 'Mali'],
        ['name' => 'Koulikoro', 'country' => 'Mali'],
        ['name' => 'Kolokani', 'country' => 'Mali'],
        ['name' => 'Kidal', 'country' => 'Mali'],
        ['name' => 'Bamako', 'country' => 'Mali'],
        ['name' => 'Gao', 'country' => 'Mali'],
        ['name' => 'Tessalit', 'country' => 'Mali'],
        ['name' => 'Ansongo', 'country' => 'Mali'],
        ['name' => 'Kati', 'country' => 'Mali'],
        ['name' => 'Bougouni', 'country' => 'Mali'],
        ['name' => 'Bla', 'country' => 'Mali'],
        ['name' => 'Bandiagara', 'country' => 'Mali'],
        ['name' => 'Nara', 'country' => 'Mali'],
        ['name' => 'San', 'country' => 'Mali'],
        ['name' => 'Markala', 'country' => 'Mali'],
        ['name' => 'Djenné', 'country' => 'Mali'],
        ['name' => 'Tombouctou', 'country' => 'Mali'],
        ['name' => 'Goundam', 'country' => 'Mali'],
        ['name' => 'Koutiala', 'country' => 'Mali'],
        ['name' => 'Niono', 'country' => 'Mali'],
        ['name' => 'Ségou', 'country' => 'Mali'],
        ['name' => 'Yorosso', 'country' => 'Mali'],
        ['name' => 'Koulikoro', 'country' => 'Mali'],
        ['name' => 'Kolokani', 'country' => 'Mali'],
    ],
    'Democratic Republic of the Congo' => [
        ['name' => 'Kinshasa', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Lubumbashi', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Mbuji-Mayi', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Kananga', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Kisangani', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Bukavu', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Tshikapa', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Kolwezi', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Likasi', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Goma', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Uvira', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Bunia', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Kikwit', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Boma', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Isiro', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Mbandaka', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Matadi', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Kalemie', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Beni', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Butembo', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Owando', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Gemena', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Mwene-Ditu', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Bandundu', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Lisala', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Baraka', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Kasongo', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Kipushi', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Ilebo', 'country' => 'Democratic Republic of the Congo'],
        ['name' => 'Kindu', 'country' => 'Democratic Republic of the Congo']
    ],
    'Italy' => [
        ['name' => 'Rome', 'country' => 'Italy'],
        ['name' => 'Milan', 'country' => 'Italy'],
        ['name' => 'Naples', 'country' => 'Italy'],
        ['name' => 'Turin', 'country' => 'Italy'],
        ['name' => 'Palermo', 'country' => 'Italy'],
        ['name' => 'Genoa', 'country' => 'Italy'],
        ['name' => 'Bologna', 'country' => 'Italy'],
        ['name' => 'Florence', 'country' => 'Italy'],
        ['name' => 'Venice', 'country' => 'Italy'],
        ['name' => 'Verona', 'country' => 'Italy'],
        ['name' => 'Padua', 'country' => 'Italy'],
        ['name' => 'Trieste', 'country' => 'Italy'],
        ['name' => 'Brescia', 'country' => 'Italy'],
        ['name' => 'Catania', 'country' => 'Italy'],
        ['name' => 'Cagliari', 'country' => 'Italy'],
        ['name' => 'Messina', 'country' => 'Italy'],
        ['name' => 'Taranto', 'country' => 'Italy'],
        ['name' => 'Reggio Calabria', 'country' => 'Italy'],
        ['name' => 'Modena', 'country' => 'Italy'],
        ['name' => 'Livorno', 'country' => 'Italy'],
        ['name' => 'Foggia', 'country' => 'Italy'],
        ['name' => 'Ravenna', 'country' => 'Italy'],
        ['name' => 'Salerno', 'country' => 'Italy'],
        ['name' => 'Ferrara', 'country' => 'Italy'],
        ['name' => 'Sassari', 'country' => 'Italy'],
        ['name' => 'Latina', 'country' => 'Italy'],
        ['name' => 'Monza', 'country' => 'Italy'],
        ['name' => 'Bergamo', 'country' => 'Italy'],
        ['name' => 'Trento', 'country' => 'Italy'],
        ['name' => 'Vicenza', 'country' => 'Italy'],
        ['name' => 'Rimini', 'country' => 'Italy'],
        ['name' => 'Piacenza', 'country' => 'Italy'],
        ['name' => 'Novara', 'country' => 'Italy'],
        ['name' => 'Ancona', 'country' => 'Italy'],
        ['name' => 'Lecce', 'country' => 'Italy'],
        ['name' => 'Bolzano', 'country' => 'Italy'],
        ['name' => 'Catanzaro', 'country' => 'Italy'],
        ['name' => 'La Spezia', 'country' => 'Italy'],
        ['name' => 'Udine', 'country' => 'Italy'],
        ['name' => 'Andria', 'country' => 'Italy'],
        ['name' => 'Brindisi', 'country' => 'Italy'],
        ['name' => 'Treviso', 'country' => 'Italy'],
        ['name' => 'Barletta', 'country' => 'Italy'],
        ['name' => 'Pisa', 'country' => 'Italy'],
        ['name' => 'Pesaro', 'country' => 'Italy'],
        ['name' => 'Reggio Emilia', 'country' => 'Italy'],
        ['name' => 'Ragusa', 'country' => 'Italy'],
        ['name' => 'Cosenza', 'country' => 'Italy'],
        ['name' => 'Viterbo', 'country' => 'Italy'],
        ['name' => 'Imola', 'country' => 'Italy'],
        ['name' => 'Carpi', 'country' => 'Italy'],
        ['name' => 'Molfetta', 'country' => 'Italy'],
        ['name'=> "Toscana", 'country'=> 'Italy']
    ],
    'Switzerland' => [
        ['name' => 'Zurich', 'country' => 'Switzerland'],
        ['name' => 'Geneva', 'country' => 'Switzerland'],
        ['name' => 'Basel', 'country' => 'Switzerland'],
        ['name' => 'Lausanne', 'country' => 'Switzerland'],
        ['name' => 'Bern', 'country' => 'Switzerland'],
        ['name' => 'Lucerne', 'country' => 'Switzerland'],
        ['name' => 'St. Gallen', 'country' => 'Switzerland'],
        ['name' => 'Lugano', 'country' => 'Switzerland'],
        ['name' => 'Winterthur', 'country' => 'Switzerland'],
        ['name' => 'Baden', 'country' => 'Switzerland'],
        ['name' => 'Sion', 'country' => 'Switzerland'],
        ['name' => 'Thun', 'country' => 'Switzerland'],
        ['name' => 'Köniz', 'country' => 'Switzerland'],
        ['name' => 'Chur', 'country' => 'Switzerland'],
        ['name' => 'Neuchâtel', 'country' => 'Switzerland'],
        ['name' => 'Uster', 'country' => 'Switzerland'],
        ['name' => 'Sierre', 'country' => 'Switzerland'],
        ['name' => 'Lancy', 'country' => 'Switzerland'],
        ['name' => 'Zug', 'country' => 'Switzerland'],
        ['name' => 'Rapperswil-Jona', 'country' => 'Switzerland'],
        ['name' => 'Montreux', 'country' => 'Switzerland'],
        ['name' => 'Vernier', 'country' => 'Switzerland'],
        ['name' => 'Schaffhausen', 'country' => 'Switzerland'],
        ['name' => 'Fribourg', 'country' => 'Switzerland'],
        ['name' => 'Cham', 'country' => 'Switzerland'],
        ['name' => 'La Chaux-de-Fonds', 'country' => 'Switzerland'],
        ['name' => 'Emmen', 'country' => 'Switzerland'],
        ['name' => 'Yverdon-les-Bains', 'country' => 'Switzerland'],
        ['name' => 'Kriens', 'country' => 'Switzerland'],
    ],
    'Canada' => [
        ['name' => 'Toronto', 'country' => 'Canada'],
        ['name' => 'Montreal', 'country' => 'Canada'],
        ['name' => 'Vancouver', 'country' => 'Canada'],
        ['name' => 'Calgary', 'country' => 'Canada'],
        ['name' => 'Edmonton', 'country' => 'Canada'],
        ['name' => 'Ottawa', 'country' => 'Canada'],
        ['name' => 'Quebec City', 'country' => 'Canada'],
        ['name' => 'Winnipeg', 'country' => 'Canada'],
        ['name' => 'Hamilton', 'country' => 'Canada'],
        ['name' => 'London', 'country' => 'Canada'],
        ['name' => 'Kitchener', 'country' => 'Canada'],
        ['name' => 'Victoria', 'country' => 'Canada'],
        ['name' => 'Halifax', 'country' => 'Canada'],
        ['name' => 'Oshawa', 'country' => 'Canada'],
        ['name' => 'Windsor', 'country' => 'Canada'],
        ['name' => 'Saskatoon', 'country' => 'Canada'],
        ['name' => 'Regina', 'country' => 'Canada'],
        ['name' => 'St. John\'s', 'country' => 'Canada'],
        ['name' => 'Barrie', 'country' => 'Canada'],
        ['name' => 'Kelowna', 'country' => 'Canada'],
        ['name' => 'Abbotsford', 'country' => 'Canada'],
        ['name' => 'Sherbrooke', 'country' => 'Canada'],
        ['name' => 'Trois-Rivières', 'country' => 'Canada'],
        ['name' => 'Guelph', 'country' => 'Canada'],
        ['name' => 'Kingston', 'country' => 'Canada'],
        ['name' => 'Moncton', 'country' => 'Canada'],
        ['name' => 'Sudbury', 'country' => 'Canada'],
        ['name' => 'Thunder Bay', 'country' => 'Canada'],
        ['name' => 'Lethbridge', 'country' => 'Canada'],
        ['name' => 'St. Catharines', 'country' => 'Canada'],
        ['name' => 'Peterborough', 'country' => 'Canada'],
        ['name' => 'Kamloops', 'country' => 'Canada'],
        ['name' => 'Chilliwack', 'country' => 'Canada'],
        ['name' => 'Red Deer', 'country' => 'Canada'],
        ['name' => 'Brantford', 'country' => 'Canada'],
        ['name' => 'Saint-Hyacinthe', 'country' => 'Canada'],
        ['name' => 'Cape Breton', 'country' => 'Canada'],
        ['name' => 'Drummondville', 'country' => 'Canada'],
    ],
    'South Korea' => [
        ['name' => 'Séoul', 'country' => 'South Korea'],
        ['name' => 'Busan', 'country' => 'South Korea'],
        ['name' => 'Incheon', 'country' => 'South Korea'],
        ['name' => 'Daegu', 'country' => 'South Korea'],
        ['name' => 'Daejeon', 'country' => 'South Korea'],
        ['name' => 'Gwangju', 'country' => 'South Korea'],
        ['name' => 'Ulsan', 'country' => 'South Korea'],
        ['name' => 'Suwon', 'country' => 'South Korea'],
        ['name' => 'Goyang', 'country' => 'South Korea'],
        ['name' => 'Seongnam', 'country' => 'South Korea'],
        ['name' => 'Yongin', 'country' => 'South Korea'],
        ['name' => 'Bucheon', 'country' => 'South Korea'],
        ['name' => 'Ansan', 'country' => 'South Korea'],
        ['name' => 'Cheongju', 'country' => 'South Korea'],
        ['name' => 'Pohang', 'country' => 'South Korea'],
        ['name' => 'Jeonju', 'country' => 'South Korea'],
        ['name' => 'Cheonan', 'country' => 'South Korea'],
        ['name' => 'Changwon', 'country' => 'South Korea'],
        ['name' => 'Yeosu', 'country' => 'South Korea'],
        ['name' => 'Wonju', 'country' => 'South Korea'],
        ['name' => 'Andong', 'country' => 'South Korea'],
        ['name' => 'Gimhae', 'country' => 'South Korea'],
        ['name' => 'Mokpo', 'country' => 'South Korea'],
        ['name' => 'Guri', 'country' => 'South Korea'],
        ['name' => 'Gunsan', 'country' => 'South Korea'],
        ['name' => 'Jeju', 'country' => 'South Korea'],
        ['name' => 'Iksan', 'country' => 'South Korea'],
        ['name' => 'Suncheon', 'country' => 'South Korea'],
        ['name' => 'Namyangju', 'country' => 'South Korea'],
        ['name' => 'Anyang', 'country' => 'South Korea'],
    ],
    'Morocco' => [
        ['name' => 'Casablanca', 'country' => 'Morocco'],
        ['name' => 'Rabat', 'country' => 'Morocco'],
        ['name' => 'Fes', 'country' => 'Morocco'],
        ['name' => 'Marrakech', 'country' => 'Morocco'],
        ['name' => 'Tangier', 'country' => 'Morocco'],
        ['name' => 'Agadir', 'country' => 'Morocco'],
        ['name' => 'Meknes', 'country' => 'Morocco'],
        ['name' => 'Oujda', 'country' => 'Morocco'],
        ['name' => 'Kenitra', 'country' => 'Morocco'],
        ['name' => 'Sale', 'country' => 'Morocco'],
        ['name' => 'Nador', 'country' => 'Morocco'],
        ['name' => 'Al Hoceima', 'country' => 'Morocco'],
        ['name' => 'Beni Mellal', 'country' => 'Morocco'],
        ['name' => 'Tetouan', 'country' => 'Morocco'],
        ['name' => 'Settat', 'country' => 'Morocco'],
        ['name' => 'Ouarzazate', 'country' => 'Morocco'],
        ['name' => 'Safi', 'country' => 'Morocco'],
        ['name' => 'El Jadida', 'country' => 'Morocco'],
        ['name' => 'Khouribga', 'country' => 'Morocco'],
        ['name' => 'Berrechid', 'country' => 'Morocco'],
        ['name' => 'Taourirt', 'country' => 'Morocco'],
        ['name' => 'Taza', 'country' => 'Morocco'],
        ['name' => 'Essaouira', 'country' => 'Morocco'],
        ['name' => 'Jerada', 'country' => 'Morocco'],
        ['name' => 'Fquih Ben Salah', 'country' => 'Morocco'],
        ['name' => 'Dakhla', 'country' => 'Morocco'],
        ['name' => 'Mohammedia', 'country' => 'Morocco'],
        ['name' => 'Khemisset', 'country' => 'Morocco'],
        ['name' => 'Taroudant', 'country' => 'Morocco'],
    ],
    'Nigeria' => [
        ['name' => 'Lagos', 'country' => 'Nigeria'],
        ['name' => 'Kano', 'country' => 'Nigeria'],
        ['name' => 'Ibadan', 'country' => 'Nigeria'],
        ['name' => 'Abuja', 'country' => 'Nigeria'],
        ['name' => 'Port Harcourt', 'country' => 'Nigeria'],
        ['name' => 'Benin City', 'country' => 'Nigeria'],
        ['name' => 'Kaduna', 'country' => 'Nigeria'],
        ['name' => 'Zaria', 'country' => 'Nigeria'],
        ['name' => 'Maiduguri', 'country' => 'Nigeria'],
        ['name' => 'Enugu', 'country' => 'Nigeria'],
    ],
    'Côte d\'Ivoire' => [
        ['name' => 'Abidjan', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'Bouaké', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'Daloa', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'Yamoussoukro', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'San Pedro', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'Korhogo', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'Man', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'Abengourou', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'Divo', 'country' => 'Côte d\'Ivoire'],
        ['name' => 'Gagnoa', 'country' => 'Côte d\'Ivoire'],
    ],
    'Cameroun' => [
        ['name' => 'Yaoundé', 'country' => 'Cameroun'],
        ['name' => 'Douala', 'country' => 'Cameroun'],
        ['name' => 'Bamenda', 'country' => 'Cameroun'],
        ['name' => 'Bafoussam', 'country' => 'Cameroun'],
        ['name' => 'Garoua', 'country' => 'Cameroun'],
        ['name' => 'Maroua', 'country' => 'Cameroun'],
        ['name' => 'Ngaoundéré', 'country' => 'Cameroun'],
        ['name' => 'Kribi', 'country' => 'Cameroun'],
        ['name' => 'Bertoua', 'country' => 'Cameroun'],
        ['name' => 'Ebolowa', 'country' => 'Cameroun'],
    ],
    'Spain' => [
        ['name' => 'Madrid', 'country' => 'Spain'],
        ['name' => 'Barcelona', 'country' => 'Spain'],
        ['name' => 'Valencia', 'country' => 'Spain'],
        ['name' => 'Seville', 'country' => 'Spain'],
        ['name' => 'Zaragoza', 'country' => 'Spain'],
        ['name' => 'Malaga', 'country' => 'Spain'],
        ['name' => 'Murcia', 'country' => 'Spain'],
        ['name' => 'Palma de Mallorca', 'country' => 'Spain'],
        ['name' => 'Las Palmas de Gran Canaria', 'country' => 'Spain'],
        ['name' => 'Bilbao', 'country' => 'Spain'],
    ],
    'Portugal' => [
        ['name' => 'Lisbon', 'country' => 'Portugal'],
        ['name' => 'Porto', 'country' => 'Portugal'],
        ['name' => 'Vila Nova de Gaia', 'country' => 'Portugal'],
        ['name' => 'Amadora', 'country' => 'Portugal'],
        ['name' => 'Braga', 'country' => 'Portugal'],
        ['name' => 'Setubal', 'country' => 'Portugal'],
        ['name' => 'Coimbra', 'country' => 'Portugal'],
        ['name' => 'Queluz', 'country' => 'Portugal'],
        ['name' => 'Funchal', 'country' => 'Portugal'],
        ['name' => 'Cacem', 'country' => 'Portugal'],
    ],
    'Luxembourg' => [
        ['name' => 'Luxembourg City', 'country' => 'Luxembourg'],
        ['name' => 'Esch-sur-Alzette', 'country' => 'Luxembourg'],
        ['name' => 'Differdange', 'country' => 'Luxembourg'],
        ['name' => 'Dudelange', 'country' => 'Luxembourg'],
        ['name' => 'Ettelbruck', 'country' => 'Luxembourg'],
        ['name' => 'Diekirch', 'country' => 'Luxembourg'],
        ['name' => 'Wiltz', 'country' => 'Luxembourg'],
        ['name' => 'Rumelange', 'country' => 'Luxembourg'],
        ['name' => 'Grevenmacher', 'country' => 'Luxembourg'],
        ['name' => 'Remich', 'country' => 'Luxembourg'],
    ],
    'Benin' => [
        ['name' => 'Cotonou', 'country' => 'Benin'],
        ['name' => 'Porto-Novo', 'country' => 'Benin'],
        ['name' => 'Parakou', 'country' => 'Benin'],
        ['name' => 'Djougou', 'country' => 'Benin'],
        ['name' => 'Bohicon', 'country' => 'Benin'],
        ['name' => 'Kandi', 'country' => 'Benin'],
        ['name' => 'Lokossa', 'country' => 'Benin'],
        ['name' => 'Ouidah', 'country' => 'Benin'],
        ['name' => 'Abomey-Calavi', 'country' => 'Benin'],
        ['name' => 'Natitingou', 'country' => 'Benin'],
    ],
    'China' => [
        ['name' => 'Shanghai', 'country' => 'China'],
        ['name' => 'Beijing', 'country' => 'China'],
        ['name' => 'Guangzhou', 'country' => 'China'],
        ['name' => 'Shenzhen', 'country' => 'China'],
        ['name' => 'Tianjin', 'country' => 'China'],
        ['name' => 'Chongqing', 'country' => 'China'],
        ['name' => 'Hangzhou', 'country' => 'China'],
        ['name' => 'Nanjing', 'country' => 'China'],
        ['name' => 'Wuhan', 'country' => 'China'],
        ['name' => 'Chengdu', 'country' => 'China'],
    ],
    'Dubai' => [
        ['name' => 'Dubai', 'country' => 'United Arab Emirates'],
    ],
    'Qatar' => [
        ['name' => 'Doha', 'country' => 'Qatar'],
    ],
    'Turkey' => [
        ['name' => 'Istanbul', 'country' => 'Turkey'],
        ['name' => 'Ankara', 'country' => 'Turkey'],
        ['name' => 'Izmir', 'country' => 'Turkey'],
        ['name' => 'Bursa', 'country' => 'Turkey'],
        ['name' => 'Adana', 'country' => 'Turkey'],
        ['name' => 'Gaziantep', 'country' => 'Turkey'],
        ['name' => 'Antalya', 'country' => 'Turkey'],
        ['name' => 'Konya', 'country' => 'Turkey'],
        ['name' => 'Eskisehir', 'country' => 'Turkey'],
        ['name' => 'Diyarbakir', 'country' => 'Turkey'],
    ],
    'Guinea' => [// conakry
        ['name' => 'Conakry', 'country' => 'Guinea'],
        ['name' => 'Nzérékoré', 'country' => 'Guinea'],
        ['name' => 'Kankan', 'country' => 'Guinea'],
        ['name' => 'Kindia', 'country' => 'Guinea'],
        ['name' => 'Labé', 'country' => 'Guinea'],
        ['name' => 'Boke', 'country' => 'Guinea'],
        ['name' => 'Mamou', 'country' => 'Guinea'],
        ['name' => 'Fria', 'country' => 'Guinea'],
        ['name' => 'Kissidougou', 'country' => 'Guinea'],
        ['name' => 'Gueckedou', 'country' => 'Guinea'],
    ],
    'Germany' => [
        ['name' => 'Berlin', 'country' => 'Germany'],
        ['name' => 'Hamburg', 'country' => 'Germany'],
        ['name' => 'Munich', 'country' => 'Germany'],
        ['name' => 'Cologne', 'country' => 'Germany'],
        ['name' => 'Frankfurt', 'country' => 'Germany'],
        ['name' => 'Stuttgart', 'country' => 'Germany'],
        ['name' => 'Düsseldorf', 'country' => 'Germany'],
        ['name' => 'Leipzig', 'country' => 'Germany'],
        ['name' => 'Dortmund', 'country' => 'Germany'],
        ['name' => 'Essen', 'country' => 'Germany'],
    ],                      
    'Brazil' => [
        ['name' => 'São Paulo', 'country' => 'Brazil'],
        ['name' => 'Rio de Janeiro', 'country' => 'Brazil'],
        ['name' => 'Brasília', 'country' => 'Brazil'],
        ['name' => 'Salvador', 'country' => 'Brazil'],
        ['name' => 'Fortaleza', 'country' => 'Brazil'],
        ['name' => 'Belo Horizonte', 'country' => 'Brazil'],
        ['name' => 'Manaus', 'country' => 'Brazil'],
        ['name' => 'Curitiba', 'country' => 'Brazil'],
        ['name' => 'Recife', 'country' => 'Brazil'],
        ['name' => 'Porto Alegre', 'country' => 'Brazil'],
    ],
    'Cape Verde' => [
        ['name' => 'Praia', 'country' => 'Cape Verde'],
        ['name' => 'Mindelo', 'country' => 'Cape Verde'],
        ['name' => 'Santa Maria', 'country' => 'Cape Verde'],
        ['name' => 'Assomada', 'country' => 'Cape Verde'],
        ['name' => 'Tarrafal', 'country' => 'Cape Verde'],
        ['name' => 'Espargos', 'country' => 'Cape Verde'],
        ['name' => 'Cidade Velha', 'country' => 'Cape Verde'],
        ['name' => 'Porto Novo', 'country' => 'Cape Verde'],
        ['name' => 'São Filipe', 'country' => 'Cape Verde'],
        ['name' => 'Santa Cruz', 'country' => 'Cape Verde'],
    ],
    'Gambia' => [
        ['name' => 'Banjul', 'country' => 'Gambia'],
        ['name' => 'Serekunda', 'country' => 'Gambia'],
        ['name' => 'Brikama', 'country' => 'Gambia'],
        ['name' => 'Bakau', 'country' => 'Gambia'],
        ['name' => 'Farafenni', 'country' => 'Gambia'],
        ['name' => 'Lamin', 'country' => 'Gambia'],
        ['name' => 'Sukuta', 'country' => 'Gambia'],
        ['name' => 'Kanifing', 'country' => 'Gambia'],
        ['name' => 'Barra', 'country' => 'Gambia'],
        ['name' => 'Gunjur', 'country' => 'Gambia'],
    ],
    'Congo (Brazzaville)' => [
        ['name' => 'Brazzaville', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Pointe-Noire', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Dolisie', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Kayes', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Owando', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Ouesso', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Nkayi', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Impfondo', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Madingou', 'country' => 'Congo (Brazzaville)'],
        ['name' => 'Sibiti', 'country' => 'Congo (Brazzaville)'],
    ],
    'Ghana' => [
        ['name' => 'Accra', 'country' => 'Ghana'],
        ['name' => 'Kumasi', 'country' => 'Ghana'],
        ['name' => 'Tamale', 'country' => 'Ghana'],
        ['name' => 'Takoradi', 'country' => 'Ghana'],
        ['name' => 'Ashiaman', 'country' => 'Ghana'],
        ['name' => 'Tema', 'country' => 'Ghana'],
        ['name' => 'Obuasi', 'country' => 'Ghana'],
        ['name' => 'Cape Coast', 'country' => 'Ghana'],
        ['name' => 'Sekondi-Takoradi', 'country' => 'Ghana'],
        ['name' => 'Koforidua', 'country' => 'Ghana'],
    ],
    'Japan' => [
        ['name' => 'Tokyo', 'country' => 'Japan'],
        ['name' => 'Yokohama', 'country' => 'Japan'],
        ['name' => 'Osaka', 'country' => 'Japan'],
        ['name' => 'Nagoya', 'country' => 'Japan'],
        ['name' => 'Sapporo', 'country' => 'Japan'],
        ['name' => 'Fukuoka', 'country' => 'Japan'],
        ['name' => 'Kobe', 'country' => 'Japan'],
        ['name' => 'Kyoto', 'country' => 'Japan'],
        ['name' => 'Kawasaki', 'country' => 'Japan'],
        ['name' => 'Saitama', 'country' => 'Japan'],
    ],
    'Liberia' => [
        ['name' => 'Monrovia', 'country' => 'Liberia'],
        ['name' => 'Gbarnga', 'country' => 'Liberia'],
        ['name' => 'Buchanan', 'country' => 'Liberia'],
        ['name' => 'Yekepa', 'country' => 'Liberia'],
        ['name' => 'Kakata', 'country' => 'Liberia'],
    ]                            
];
?>
