controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
viewpoint_admin:
    resource: '@ViewpointAdminBundle/Resources/config/routes.yaml'
viewpoint_theme:
    resource: '@ViewpointThemeBundle/Resources/config/routes.yaml'
api_login_check:
    path: /api/login_check